In [68]:
#Q1
import pandas as pd

pd.__version__

'2.3.2'

In [69]:
df = pd.read_csv("car_fuel_efficiency.csv")

In [70]:
df.head()


engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [71]:
#Q2
len(df)


9704

In [72]:
#Q3
len(df.groupby("fuel_type"))

2

In [73]:
#Q4
len(df.loc[:,[(df[col].isna()).any() for col in df.columns]].columns)

4

In [74]:
#Q5
df[df["origin"] == "Asia"].agg({"fuel_efficiency_mpg":"max"})

fuel_efficiency_mpg    23.759123
dtype: float64

In [75]:
#Q6
init_median_horsepower = df["horsepower"].median()
init_median_horsepower

np.float64(149.0)

In [76]:
most_freq_horsepower = df["horsepower"].mode()[0]
most_freq_horsepower

np.float64(152.0)

In [77]:
df["horsepower"] = df["horsepower"].fillna(most_freq_horsepower)

In [78]:
df["horsepower"]

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [79]:
later_median_horsepower = df["horsepower"].median()
later_median_horsepower

np.float64(152.0)

In [91]:
#Q7
asia_cars_df = df[df["origin"] == "Asia"]
asia_cars_df[["vehicle_weight", "model_year"]].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [119]:
asia_numpy = asia_cars_df[["vehicle_weight", "model_year"]].head(7).values 
asia_numpy
X = asia_numpy

In [121]:
XT = X.T
XTX = XT.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [122]:
import numpy as np
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [123]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [126]:
temp = inv_XTX.dot(X.T)
W = temp.dot(y)
W

array([0.01386421, 0.5049067 ])

In [127]:
np.sum(W)

np.float64(0.5187709081074016)